// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OrderManagement.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class OrderManagementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Order management", "    As office staff\r\n    I want to create and maintain orders for existing custom" +
                "ers\r\n    So that we can record what a customer has bought and for how much", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Orders.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("a customer \"CU30001\" named \"Jane Doe\" is already registered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("the article group \"Furniture\" exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("article \"ART-40001\" named \"Oak Table\" already exists in group \"Furniture\" priced " +
                    "at 120.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("article \"ART-40002\" named \"Oak Chair\" already exists in group \"Furniture\" priced " +
                    "at 45.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Orders.feature.ndjson", 18);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Creating an order for an existing customer with one valid article")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Creating an order for an existing customer with one valid article")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task CreatingAnOrderForAnExistingCustomerWithOneValidArticle()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creating an order for an existing customer with one valid article", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table3.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 13
    await testRunner.WhenAsync("I create order \"ORD-2026-001\" for customer \"CU30001\" with lines:", ((string)(null)), table3, "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("order \"ORD-2026-001\" is created successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("order \"ORD-2026-001\" has 1 order line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("the total for order \"ORD-2026-001\" is 120.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order can contain multiple lines")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order can contain multiple lines")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderCanContainMultipleLines()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order can contain multiple lines", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table4.AddRow(new string[] {
                            "ART-40001",
                            "1"});
                table4.AddRow(new string[] {
                            "ART-40002",
                            "2"});
#line 21
    await testRunner.WhenAsync("I create order \"ORD-2026-002\" for customer \"CU30001\" with lines:", ((string)(null)), table4, "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("order \"ORD-2026-002\" is created successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("order \"ORD-2026-002\" has 2 order lines", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("the total for order \"ORD-2026-002\" is 210.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Quantity must be greater than zero")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Quantity must be greater than zero")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task QuantityMustBeGreaterThanZero()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Quantity must be greater than zero", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table5.AddRow(new string[] {
                            "ART-40001",
                            "0"});
#line 30
    await testRunner.WhenAsync("I create order \"ORD-2026-003\" for customer \"CU30001\" with lines:", ((string)(null)), table5, "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("the order creation is rejected because the quantity must be positive", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order cannot reference a nonexistent customer")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order cannot reference a nonexistent customer")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderCannotReferenceANonexistentCustomer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order cannot reference a nonexistent customer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table6.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 36
    await testRunner.WhenAsync("I create order \"ORD-2026-004\" for an unknown customer with lines:", ((string)(null)), table6, "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the order creation is rejected because the customer was not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order line cannot reference a nonexistent article")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order line cannot reference a nonexistent article")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderLineCannotReferenceANonexistentArticle()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order line cannot reference a nonexistent article", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.WhenAsync("I create order \"ORD-2026-005\" for customer \"CU30001\" with an unknown article and " +
                        "quantity 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
    await testRunner.ThenAsync("the order creation is rejected because the article was not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Duplicate order numbers are rejected")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Duplicate order numbers are rejected")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task DuplicateOrderNumbersAreRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Duplicate order numbers are rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table7.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 46
    await testRunner.GivenAsync("order \"ORD-2026-006\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table7, "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table8.AddRow(new string[] {
                            "ART-40002",
                            "1"});
#line 49
    await testRunner.WhenAsync("I create order \"ORD-2026-006\" for customer \"CU30001\" with lines:", ((string)(null)), table8, "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("the order creation is rejected because the order number already exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("The order total equals the sum of line quantity multiplied by snapshotted unit pr" +
            "ice")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The order total equals the sum of line quantity multiplied by snapshotted unit pr" +
            "ice")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task TheOrderTotalEqualsTheSumOfLineQuantityMultipliedBySnapshottedUnitPrice()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The order total equals the sum of line quantity multiplied by snapshotted unit pr" +
                    "ice", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table9.AddRow(new string[] {
                            "ART-40001",
                            "2"});
                table9.AddRow(new string[] {
                            "ART-40002",
                            "3"});
#line 55
    await testRunner.WhenAsync("I create order \"ORD-2026-007\" for customer \"CU30001\" with lines:", ((string)(null)), table9, "When ");
#line hidden
#line 59
    await testRunner.ThenAsync("the total for order \"ORD-2026-007\" is 375.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Editing order lines recalculates the total")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Editing order lines recalculates the total")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task EditingOrderLinesRecalculatesTheTotal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editing order lines recalculates the total", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table10.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 62
    await testRunner.GivenAsync("order \"ORD-2026-008\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table10, "Given ");
#line hidden
#line 65
    await testRunner.WhenAsync("I change the quantity of article \"ART-40001\" on order \"ORD-2026-008\" to 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("the total for order \"ORD-2026-008\" is 360.00 CHF", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order can be found by its order number")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order can be found by its order number")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderCanBeFoundByItsOrderNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order can be found by its order number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table11.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 69
    await testRunner.GivenAsync("order \"ORD-2026-009\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table11, "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync("I search orders for \"ORD-2026-009\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("the order search returns exactly order \"ORD-2026-009\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Orders can be searched or listed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Orders can be searched or listed")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task OrdersCanBeSearchedOrListed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Orders can be searched or listed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table12.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 76
    await testRunner.GivenAsync("order \"ORD-2026-010\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table12, "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table13.AddRow(new string[] {
                            "ART-40002",
                            "1"});
#line 79
    await testRunner.AndAsync("order \"ORD-2026-011\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table13, "And ");
#line hidden
#line 82
    await testRunner.WhenAsync("I list all orders", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("the order list contains \"ORD-2026-010\" and \"ORD-2026-011\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Deleting an order also removes its order lines")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Deleting an order also removes its order lines")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task DeletingAnOrderAlsoRemovesItsOrderLines()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deleting an order also removes its order lines", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 85
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table14.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 86
    await testRunner.GivenAsync("order \"ORD-2026-012\" already exists for customer \"CU30001\" with lines:", ((string)(null)), table14, "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("I delete order \"ORD-2026-012\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("order \"ORD-2026-012\" can no longer be found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("A failed operation does not leave partially persisted data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A failed operation does not leave partially persisted data")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AFailedOperationDoesNotLeavePartiallyPersistedData()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed operation does not leave partially persisted data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table15.AddRow(new string[] {
                            "ART-40001",
                            "1"});
                table15.AddRow(new string[] {
                            "ART-40002",
                            "0"});
#line 93
    await testRunner.WhenAsync("I create order \"ORD-2026-013\" for customer \"CU30001\" with lines:", ((string)(null)), table15, "When ");
#line hidden
#line 97
    await testRunner.ThenAsync("the order creation is rejected because the quantity must be positive", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
    await testRunner.AndAsync("order \"ORD-2026-013\" can not be found by search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order resolves the customer address valid on the delivery date")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order resolves the customer address valid on the delivery date")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderResolvesTheCustomerAddressValidOnTheDeliveryDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order resolves the customer address valid on the delivery date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 100
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 101
    await testRunner.GivenAsync("a customer \"CU30020\" is registered with address \"Old Street 1, 8000 Zurich, CH\" v" +
                        "alid from \"2026-01-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
    await testRunner.AndAsync("customer \"CU30020\" moved to \"New Street 5, 9000 St. Gallen, CH\" valid from \"2026-" +
                        "09-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table16.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 103
    await testRunner.WhenAsync("I create order \"ORD-2026-020\" for customer \"CU30020\" with delivery date \"2026-08-" +
                        "31\" and lines:", ((string)(null)), table16, "When ");
#line hidden
#line 106
    await testRunner.ThenAsync("order \"ORD-2026-020\" has billing address \"Old Street 1, 8000 Zurich, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
    await testRunner.AndAsync("order \"ORD-2026-020\" has delivery address \"Old Street 1, 8000 Zurich, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("An order resolves the new address once it becomes valid on the delivery date")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An order resolves the new address once it becomes valid on the delivery date")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task AnOrderResolvesTheNewAddressOnceItBecomesValidOnTheDeliveryDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An order resolves the new address once it becomes valid on the delivery date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 109
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 110
    await testRunner.GivenAsync("a customer \"CU30021\" is registered with address \"Old Street 1, 8000 Zurich, CH\" v" +
                        "alid from \"2026-01-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
    await testRunner.AndAsync("customer \"CU30021\" moved to \"New Street 5, 9000 St. Gallen, CH\" valid from \"2026-" +
                        "09-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table17.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 112
    await testRunner.WhenAsync("I create order \"ORD-2026-021\" for customer \"CU30021\" with delivery date \"2026-09-" +
                        "01\" and lines:", ((string)(null)), table17, "When ");
#line hidden
#line 115
    await testRunner.ThenAsync("order \"ORD-2026-021\" has billing address \"New Street 5, 9000 St. Gallen, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
    await testRunner.AndAsync("order \"ORD-2026-021\" has delivery address \"New Street 5, 9000 St. Gallen, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Billing and delivery addresses can be overridden independently")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Billing and delivery addresses can be overridden independently")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task BillingAndDeliveryAddressesCanBeOverriddenIndependently()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Billing and delivery addresses can be overridden independently", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 118
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table18.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 119
    await testRunner.WhenAsync("I create order \"ORD-2026-022\" for customer \"CU30001\" with delivery date \"2026-09-" +
                        "01\", billing address \"Billing Street 1, 8000 Zurich, CH\" and delivery address \"D" +
                        "elivery Street 2, 9000 St. Gallen, CH\" and lines:", ((string)(null)), table18, "When ");
#line hidden
#line 122
    await testRunner.ThenAsync("order \"ORD-2026-022\" has billing address \"Billing Street 1, 8000 Zurich, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.AndAsync("order \"ORD-2026-022\" has delivery address \"Delivery Street 2, 9000 St. Gallen, CH" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.AndAsync("the billing address for order \"ORD-2026-022\" is manual", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.AndAsync("the delivery address for order \"ORD-2026-022\" is manual", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("A submitted order keeps its resolved address snapshots when reopened")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A submitted order keeps its resolved address snapshots when reopened")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Order management")]
        public async global::System.Threading.Tasks.Task ASubmittedOrderKeepsItsResolvedAddressSnapshotsWhenReopened()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A submitted order keeps its resolved address snapshots when reopened", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 127
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "ArticleNumber",
                            "Quantity"});
                table19.AddRow(new string[] {
                            "ART-40001",
                            "1"});
#line 128
    await testRunner.WhenAsync("I create order \"ORD-2026-023\" for customer \"CU30001\" with delivery date \"2026-09-" +
                        "01\" and lines:", ((string)(null)), table19, "When ");
#line hidden
#line 131
    await testRunner.ThenAsync("order \"ORD-2026-023\" has billing address \"Main Street 1, 8000 Zurich, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
    await testRunner.AndAsync("order \"ORD-2026-023\" has delivery address \"Main Street 1, 8000 Zurich, CH\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
    await testRunner.AndAsync("the billing address for order \"ORD-2026-023\" is automatic", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.AndAsync("the delivery address for order \"ORD-2026-023\" is automatic", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
