trigger:
  branches:
    include:
      - Develop
      - feature/*
      - Feature*

pr:
  branches:
    include:
      - Develop

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 9.x

- script: dotnet restore
  displayName: Restore

- script: dotnet test --configuration Release --no-restore
  displayName: Run tests
