<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="bunit" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OrderManagement.Application\OrderManagement.Application.csproj" />
        <ProjectReference Include="..\..\src\OrderManagement.Presentation.Blazor\OrderManagement.Presentation.Blazor.csproj" />
    </ItemGroup>

</Project>
